# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOrAnjHSHH33dxZnSERd569ygZV9sfSP
"""

import pandas as pd
df = pd.read_csv('/content/Housing.csv')
df.info()  # Get data types and non-null counts
df.describe()  # Basic stats

numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

df[numerical_columns] = df[numerical_columns].fillna(df[numerical_columns].mean())

df.dropna(inplace=True)

# Impute missing values for numerical columns only
df[numerical_columns] = df[numerical_columns].fillna(df[numerical_columns].mean())

# Drop rows with any remaining missing values
df.dropna(inplace=True)

df.drop_duplicates(inplace=True)

import seaborn as sns
sns.boxplot(x=df['parking'])
# Identify outliers and remove or adjust them

df['price'] = pd.to_datetime(df['price'])  # Convert to datetime
df['area'] = df['area'].astype('category')  # Convert to categorical

df = pd.get_dummies(df, columns=['price'])  # One-hot encoding

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['area'] = scaler.fit_transform(df[['area']])